services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: "postgresql://electivoia:electivoia2024@database:5432/electivoia?serverVersion=16&charset=utf8"
      MESSENGER_TRANSPORT_DSN: "doctrine://default?auto_setup=0"
      MAILER_DSN: ${MAILER_DSN:-null://null}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      TRUSTED_PROXIES: "127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
      TRUSTED_HOSTS: ".*"
      MAILER_FROM: ${MAILER_FROM:-noreply@electivoia.cl}
    ports:
      - "8888:80"

  database:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-electivoia}
      POSTGRES_USER: ${POSTGRES_USER:-electivoia}
      POSTGRES_PASSWORD: electivoia2024
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-electivoia}", "-U", "${POSTGRES_USER:-electivoia}"]
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  messenger:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: "postgresql://electivoia:electivoia2024@database:5432/electivoia?serverVersion=16&charset=utf8"
      MESSENGER_TRANSPORT_DSN: "doctrine://default?auto_setup=0"
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      TRUSTED_PROXIES: "127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
      TRUSTED_HOSTS: ".*"
      MAILER_FROM: ${MAILER_FROM:-noreply@electivoia.cl}
    command: php bin/console messenger:consume async --time-limit=3600 --memory-limit=128M

volumes:
  database_data:
